//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class renta
    {
        public int idrenta { get; set; }
        public Nullable<int> idusuario { get; set; }
        public Nullable<int> idpropiedad { get; set; }
        public string status { get; set; }
        public string auxiliar { get; set; }
    
        public virtual propiedad propiedad { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
